### ISSUE TITLE
-[EAGLContext flush]: unrecognized selector sent to instance 0x170231980

### ISSUE THREAD

**Issue by KrLikeblue** [adamwulf/JotUI#14]
Hello,

I have used JOTView and GPUImage libraries in same project.

so I go in a screen in which I have used Jotview library then i go back and switch to another screen in which I have used GPUImage library, then app just crashes with this reason

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[EAGLContext flush]: unrecognized selector sent to instance 0x170231980'

When I go back from screen in which I have implemented JotView, I clear jotview like this: [jotView clear:YES];

App is crashing in JotGLContext.m file at this function    [(JotGLContext*)[JotGLContext currentContext] flush];

I think your library and GPU library both are using OPENGL, that is why it is causing error.

Can you help me with this error ?

Thanks

**Comment by adamwulf** [comment]
hrm, not sure why it would be doing that. Can you post a stack trace as well?

**Comment by KrLikeblue** [comment]
What do you mean by Stack Trace ? Can you tell me more about this ?

**Comment by adamwulf** [comment]
The stack trace shows which methods are running when the crash happens. To find it - first - setup an exception breakpoint so that the debugger opens right when the crash happens. Make sure the breakpoint is set to Obj-C exceptions:

<img width="258" alt="screen shot 2017-01-14 at 4 30 55 pm" src="https://cloud.githubusercontent.com/assets/251087/21958595/5908d73c-da77-11e6-8519-65c8f4c41c64.png">

<img width="412" alt="screen shot 2017-01-14 at 4 31 17 pm" src="https://cloud.githubusercontent.com/assets/251087/21958599/5cb0da2e-da77-11e6-86cc-f133f9621bc4.png">

Then when the crash happens, highlight the thread that's crashed, and copy/paste it to this issue:

<img width="470" alt="screen shot 2017-01-14 at 4 33 48 pm" src="https://cloud.githubusercontent.com/assets/251087/21958604/7cb8839e-da77-11e6-9399-77640857b86a.png">

**Comment by djcomy** [comment]
Did You manage to fix this? I have the same issue...
Also ha GPUImage and JotUI in the same project. Here is how my app is organized:
First screen: load photo from gallery, or from camera (photo taken trough GPUImage filters)
Second screen: edit screen with some stickers addon, sliding frames, and some buttons sending taken photo to eraser option and Jot UI option.
Third screen is JotUI option... 
When photo is taken from gallery everything works fine, even though I didn't manage to get back image view that i was writing on back to second screen.
But when photo is taken with camera and GPUImage filters, app crashes with same error (-[EAGLContext flush]:......) when I tap on JotUI option screen to show up.

Hopefully I got this problem closer to You.

**Comment by CoderMaurice** [comment]
I got the same problem too.
When GPUImage is used, JotView will crash at initialization.
crash code:
>  [(JotGLContext*)[JotGLContext currentContext] flush];
    

I modified it:

>    if ([[JotGLContext currentContext] isKindOfClass:[JotGLContext class]]) {
            [(JotGLContext*)[JotGLContext currentContext] flush];
        }

**Comment by adamwulf** [comment]
Thanks for the discussion and detail on this. I've pushed up this fix at `db568d3dd3` on master
