### ISSUE TITLE
Crashed on OpenGLException: currentContext must be a JotGLContext'

### ISSUE THREAD

**Issue by OrcaData** [adamwulf/JotUI#38]
Hello Adam,

My project creates a viewController for user to draw, and a button on the view to call self.dismissViewControllerAnimated to close it and save to disk. When I use saveImage and dismiss the viewController, the next time I create a new viewController, the crash happened. Without saveImage executed, everything works fine. 

*** Terminating app due to uncaught exception 'OpenGLException', reason: 'currentContext must be a JotGLContext'

I found that whenever saveImage get called, the next time below lines of code runs cause the problem.
  [paperState loadJotStateAsynchronously:NO withSize:jotView.bounds.size andScale:[[UIScreen mainScreen] scale] andContext:jotView.context andBufferManager:[JotBufferManager sharedInstance]];

Any suggestions on finding solutions about this issue? Many thanks.

**Comment by adamwulf** [comment]
I suspect the jot view is getting deallocated when you dismiss the view controller, and then the save, which is asynchronous, doesn't have a the correct context to finish the save anymore. Just a guess, but i'd make sure that the jot view completes saving before dealloc, and that you're building a brand new jot view next time to create a view controller.

**Comment by OrcaData** [comment]
Thanks, Adam. I tried building a MainViewController and assigned a button present the JotViewController to perform drawing. And when I dismissed the JotView and opens another JotViewController, the memory increased 50MB. Every time I call a new JotView, it eats 50MB - 80MB. I'm using ARC, so the ViewController should be deallocated. I'm wondering if I can call some method to release memory usage. Is that something to do with JotBufferManager?

**Comment by adamwulf** [comment]
without access to your project, it's hard to say what the issue is. The `JotView` needs to be retained during the save, and after that can be dealloc'd. But it also sounds like your `JotViewController` isn't getting released (or the JotView of that controller isn't getting released) when you dismiss the controller. I'd poke around with Instruments memory/heap allocations tool to see what's still holding on to the memory.

The `exportImageTo` returns the UIImage for the ink/thumbnail, and the ink can be surprisingly large image since it's a full screen retina uncompressed bitmap. If you're holding onto those after every export, then that'll increase your memory as well. rough estimate: 2732x2048 pixels times 4 for RGBA is roughly 22Mb uncompressed for that ink image, so that's likely at least some of it.

**Comment by OrcaData** [comment]
Thanks, Adam. use JowView invalidate do the trick and cleared buffer properly.
